import type { RitualDefinition } from './types'

/**
 * CLEAR — releasing distraction, resentment, clutter and unwanted habits.
 *
 * The breath patterns favour a long exhale: this set is about letting go
 * rather than gathering.
 */
export const CLEAR_RITUALS: RitualDefinition[] = [
  {
    id: 'clear-emptied-table',
    intent: 'clear',
    title: 'The Emptied Table',
    opening: 'Clear the surface before you set anything down.',
    invocation: [
      'Everything is on the table at once, and so nothing has room to be worked on.',
      'I take it all off.',
      'Not solved — off. There is a difference, and the difference is the relief.',
      'One thing goes back down. Only one.',
      'Let the rest wait on the floor where it can be reached but not seen.',
      'A cleared surface is not an empty life. It is a workable one.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 0, exhale: 8, holdOut: 0 }],
    groundingActions: [
      'Clear one small surface completely and leave it empty.',
      'Close every tab except the one you need.',
      'Write the one thing you will work on next, and nothing else.',
      'Put one object back where it belongs.',
    ],
    silenceSeconds: { whisper: 14, ritual: 45, deep: 90 },
  },
  {
    id: 'clear-set-down-grudge',
    intent: 'clear',
    title: 'Set Down The Grudge',
    opening: 'You may set it down without declaring them right.',
    invocation: [
      'I have carried a resentment as though it were evidence',
      'that must one day be presented somewhere, to someone.',
      'No court is convening. I am simply carrying it.',
      'Setting it down is not forgiveness, and it is not agreement.',
      'It is only my hands opening, because they are tired and I want them for other work.',
      'Let it lie where it falls. I am going on without it.',
    ].join('\n'),
    breathPatterns: [
      { inhale: 4, holdIn: 1, exhale: 8, holdOut: 0 },
      { inhale: 4, holdIn: 0, exhale: 9, holdOut: 1 },
    ],
    groundingActions: [
      'Write the grievance out in full, then throw the paper away.',
      'Open your hands, palms up, and hold them open for a count of twenty.',
      'Delete the draft you have been rewriting in your head.',
      'Do one good thing today that has nothing to do with the argument.',
    ],
    silenceSeconds: { whisper: 17, ritual: 52, deep: 105 },
  },
  {
    id: 'clear-unanswered-pull',
    intent: 'clear',
    title: 'The Unanswered Pull',
    opening: 'A pull is not an instruction.',
    invocation: [
      'Something is pulling at me, as it does at this hour,',
      'and it has learned exactly which part of me answers.',
      'I notice the pull. I let it be a pull, and not a verdict.',
      'It rises. It crests. It goes, if it is not fed.',
      'Let me sit through the crest of it without moving my hands.',
      'It has been survived before. It will be survived again in ninety seconds.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 8, holdOut: 0 }],
    groundingActions: [
      'Wait ninety seconds before acting on the urge, and time it.',
      'Move to a different room and take five slow steps.',
      'Drink a glass of water instead, slowly.',
      'Put the object of the urge out of reach for the next hour.',
    ],
    silenceSeconds: { whisper: 15, ritual: 48, deep: 96 },
  },
  {
    id: 'clear-does-not-serve',
    intent: 'clear',
    title: 'What Does Not Serve',
    opening: 'Keep only what is load-bearing.',
    invocation: [
      'Much of what I carry is not useful, only familiar.',
      'Old arguments. Predictions I never asked for. A running commentary on myself.',
      'I ask of each one, plainly: is this load-bearing?',
      'Almost none of it is.',
      'Let me put down what is merely habitual and keep what holds the roof up.',
      'The house stands better with less in it.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 1, exhale: 7, holdOut: 1 }],
    groundingActions: [
      'Remove one recurring commitment that no longer does anything for you.',
      'Unsubscribe from one thing that reliably makes your day worse.',
      'Throw away five objects you have not used in a year.',
      'Write down one belief about yourself you are no longer going to repeat.',
    ],
    silenceSeconds: { whisper: 14, ritual: 44, deep: 88 },
  },
  {
    id: 'clear-close-loops',
    intent: 'clear',
    title: 'Close The Loops',
    opening: 'An open loop makes noise until it is closed or named.',
    invocation: [
      'There are a dozen unfinished things humming at the edge of my attention.',
      'They are loud not because they are large, but because they are open.',
      'I will name them, which quiets them, and close one, which ends it.',
      'Let the naming be honest and the list be short.',
      'Let me finish one small thing completely before I begin another.',
      'A closed loop makes no sound at all.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 7, holdOut: 0 }],
    groundingActions: [
      'Write down every unfinished thing on one page, then close one of them.',
      'Complete one unfinished task before opening another.',
      'Send the one reply that has been open for a week.',
      'Cancel one thing you were never going to do.',
    ],
    silenceSeconds: { whisper: 13, ritual: 42, deep: 86 },
  },
  {
    id: 'clear-habit-interrupted',
    intent: 'clear',
    title: 'The Habit, Interrupted',
    opening: 'Break the chain at its smallest link.',
    invocation: [
      'The habit does not begin with the act. It begins earlier,',
      'in a small automatic movement I have never looked at directly.',
      'Tonight I look at it.',
      'I put a pause where the automation used to be — one breath wide.',
      'That gap is all I need. In the gap, there is a choice.',
      'Let me take the gap tonight. Once is how it starts.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 3, exhale: 7, holdOut: 1 }],
    groundingActions: [
      'Move the object connected to the habit somewhere inconvenient.',
      'Write down the exact moment before the habit begins.',
      'Do a different small thing at the usual trigger time today.',
      'Take five slow steps the next time the urge arrives.',
    ],
    silenceSeconds: { whisper: 16, ritual: 49, deep: 98 },
  },
  {
    id: 'clear-sweep-threshold',
    intent: 'clear',
    title: 'Sweep The Threshold',
    opening: 'Clean the small square you are standing on.',
    invocation: [
      'I cannot clear the whole of it. I can clear one square of floor.',
      'So I begin there, at the threshold, with the smallest honest task.',
      'Order does not arrive by decision; it arrives by sweeping.',
      'Let the first clean surface be a place the eye can rest.',
      'Let it be small enough to actually finish.',
      'The rest of the room will follow, or it will not, and tonight that is fine.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 1, exhale: 6, holdOut: 1 }],
    groundingActions: [
      'Clear one small surface and stop when it is done.',
      'Wash whatever is in the sink right now.',
      'Put five things back where they belong.',
      'Make the bed, even at this hour.',
    ],
    silenceSeconds: { whisper: 12, ritual: 40, deep: 82 },
  },
  {
    id: 'clear-rehearsal-ended',
    intent: 'clear',
    title: 'The Rehearsal, Ended',
    opening: 'Stop performing a conversation that has not happened.',
    invocation: [
      'I have run this conversation forty times and had it none.',
      'Every version ends badly, because rehearsal is not thinking, it is bracing.',
      'I am not preparing. I am suffering it in advance, repeatedly.',
      'Let me end the performance here.',
      'When the real conversation comes I will be present for it, which is worth more than any script.',
      'The stage goes dark. Nothing has actually happened.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 8, holdOut: 0 }],
    groundingActions: [
      'Write the one sentence you actually need to say, and stop preparing.',
      'Arrange the real conversation for a specific time.',
      'Do something physical for ten minutes: walk, tidy, stretch.',
      'Say out loud: this has not happened yet.',
    ],
    silenceSeconds: { whisper: 16, ritual: 50, deep: 100 },
  },
  {
    id: 'clear-let-them-be-wrong',
    intent: 'clear',
    title: 'Let Them Be Wrong',
    opening: 'Not every error requires your correction.',
    invocation: [
      'Someone is wrong, and I have carried the wrongness for days',
      'as though it were mine to resolve.',
      'It is not. It can simply remain out there, unresolved and untouched by me.',
      'Let me stop drafting the reply that would settle it.',
      'Nothing is settled by that reply. Only my evening is spent.',
      'I release the need to be understood by everyone. I keep my evening.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 0, exhale: 8, holdOut: 1 }],
    groundingActions: [
      'Leave the comment unanswered and close the application.',
      'Write the reply somewhere it cannot be sent, then delete it.',
      'Do one thing you enjoy for fifteen minutes instead.',
      'Mute the thread for a week.',
    ],
    silenceSeconds: { whisper: 15, ritual: 47, deep: 94 },
  },
  {
    id: 'clear-fewer-things',
    intent: 'clear',
    title: 'Fewer Things',
    opening: 'Subtraction is the faster improvement.',
    invocation: [
      'I have been trying to add my way out of a problem caused by too much.',
      'More systems. More plans. More intentions.',
      'Tonight I subtract instead.',
      'One commitment released. One tab closed. One expectation lowered honestly.',
      'Let there be less, and let the less be chosen rather than lost.',
      'Space is not what remains after the work; it is what makes the work possible.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 7, holdOut: 1 }],
    groundingActions: [
      'Remove one thing from tomorrow and tell whoever needs to know.',
      'Close one unnecessary tab, and then the rest of them.',
      'Delete one app that reliably takes an hour from you.',
      'Cross one item off the list by deciding not to do it at all.',
    ],
    silenceSeconds: { whisper: 14, ritual: 43, deep: 88 },
  },
  {
    id: 'clear-break-loop',
    intent: 'clear',
    title: 'Break The Loop',
    opening: 'The thought has been going in a circle. Step off it.',
    invocation: [
      'This thought has come around six times and delivered nothing new.',
      'It is not thinking. It is a wheel turning in one place.',
      'I step off it, not by arguing, but by changing what my body is doing.',
      'Feet on the floor. Eyes on something far away. A breath longer out than in.',
      'Let the wheel keep turning without me on it.',
      'It slows when no one is riding.',
    ].join('\n'),
    breathPatterns: [
      { inhale: 4, holdIn: 0, exhale: 8, holdOut: 0 },
      { inhale: 3, holdIn: 0, exhale: 9, holdOut: 0 },
    ],
    groundingActions: [
      'Stand up and take five slow steps.',
      'Look at something at least ten metres away for thirty seconds.',
      'Wash your face in cold water.',
      'Step outside briefly, even just to the doorway.',
    ],
    silenceSeconds: { whisper: 13, ritual: 41, deep: 84 },
  },
  {
    id: 'clear-bright-rectangle',
    intent: 'clear',
    title: 'The Small Bright Rectangle',
    opening: 'Set the light down and let the eyes find the room.',
    invocation: [
      'I have given hours to a small bright rectangle and received an aftertaste.',
      'It asked nothing of me and took everything, which is its design.',
      'Let me set it down — face down, out of reach, for the length of this.',
      'Let the eyes go long. Let the room come back.',
      'There is a whole evening standing outside the glass, waiting.',
      'I will spend a little of it deliberately.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 7, holdOut: 0 }],
    groundingActions: [
      'Put the phone in another room for the next hour.',
      'Look out of a window at the furthest thing you can see.',
      'Read something printed on paper for ten minutes.',
      'Step outside briefly without taking anything with you.',
    ],
    silenceSeconds: { whisper: 16, ritual: 50, deep: 102 },
  },
  {
    id: 'clear-release-verdict',
    intent: 'clear',
    title: 'Release The Verdict',
    opening: 'You do not have to reach a judgement tonight.',
    invocation: [
      'I have been trying to decide what today meant, and whether I did well,',
      'and what kind of person the evidence suggests.',
      'No verdict is due. No verdict has ever helped.',
      'Let the day be simply a day — some of it good, some poor, most of it neither.',
      'I put down the gavel I was never appointed to hold.',
      'Unjudged, the day can finally end.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 1, exhale: 8, holdOut: 1 }],
    groundingActions: [
      'Write one neutral sentence about today, with no judgement in it.',
      'Stop reviewing the day and do one ordinary domestic task.',
      'Wash your face and end the day there.',
      'Say out loud: it was a day, and it is over.',
    ],
    silenceSeconds: { whisper: 17, ritual: 53, deep: 106 },
  },
]
