import type { RitualDefinition } from './types'

/**
 * GUARD — protection, boundaries, courage, steadiness.
 *
 * Every passage here is defensive and self-governing. Nothing in this set
 * acts upon another person.
 */
export const GUARD_RITUALS: RitualDefinition[] = [
  {
    id: 'guard-standing-line',
    intent: 'guard',
    title: 'The Standing Line',
    opening: 'Stand within what you can govern.',
    invocation: [
      'Here is the line, and I am the one who draws it.',
      'Not in anger. Not in fear. In the plain daylight of the mind.',
      'What is mine to answer for, I will answer for.',
      'What is not, I set down outside this circle.',
      'Let the line hold because I hold it,',
      'and let me keep it without cruelty.',
    ].join('\n'),
    breathPatterns: [
      { inhale: 4, holdIn: 2, exhale: 6, holdOut: 0 },
      { inhale: 4, holdIn: 4, exhale: 6, holdOut: 2 },
    ],
    groundingActions: [
      'Write down one thing that is not yours to solve, then close the notebook.',
      'Say one limit out loud, in a level voice, as you would state a fact.',
      'Stand up, plant both feet, and hold still for thirty seconds.',
      'Decline one small request today without explaining yourself twice.',
    ],
    silenceSeconds: { whisper: 15, ritual: 45, deep: 90 },
  },
  {
    id: 'guard-iron-quiet',
    intent: 'guard',
    title: 'Iron Quiet',
    opening: 'Something loud has come near. Meet it with weight, not volume.',
    invocation: [
      'Something loud has come near me, and it wants an equal noise.',
      'It will not receive one.',
      'I have a quieter thing: a floor beneath the feet, a breath that does not hurry.',
      'Let me be difficult to move and easy to be near.',
      'Let the iron in me be structure and never a weapon.',
      'I keep my ground. I keep my temper. Both are mine to keep.',
    ].join('\n'),
    breathPatterns: [
      { inhale: 4, holdIn: 2, exhale: 6, holdOut: 0 },
      { inhale: 5, holdIn: 2, exhale: 7, holdOut: 0 },
    ],
    groundingActions: [
      'Wait one full hour before answering the message that provoked you.',
      'Drink a glass of water slowly, standing still, before you reply to anything.',
      'Write the angry reply somewhere it cannot be sent, then delete it.',
      'Lower your voice deliberately in the next conversation you have.',
    ],
    silenceSeconds: { whisper: 16, ritual: 48, deep: 95 },
  },
  {
    id: 'guard-threshold-watch',
    intent: 'guard',
    title: 'The Threshold Watch',
    opening: 'Some doors are held closed by attention alone.',
    invocation: [
      'I stand at the edge of my own hours and watch what asks to enter.',
      'Not everything that knocks is owed a room.',
      'I will admit the work that is honest, the voice that is kind,',
      'and the difficulty I have chosen to carry.',
      'The rest may wait outside the door and grow tired of waiting.',
      'I am the keeper here. The keeping begins now.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 3, exhale: 6, holdOut: 1 }],
    groundingActions: [
      'Silence notifications for the next hour and put the phone in another room.',
      'Choose the one task you will admit into this evening, and name it aloud.',
      'Close the door of the room you are in, deliberately.',
      'Write the single sentence you will say if you are asked to take on more.',
    ],
    silenceSeconds: { whisper: 14, ritual: 44, deep: 88 },
  },
  {
    id: 'guard-unshaken',
    intent: 'guard',
    title: 'Unshaken',
    opening: 'Fear is a weather. Stand as a house stands.',
    invocation: [
      'The fear arrived before the thing itself, as it always does.',
      'I do not argue with it. I do not obey it either.',
      'I have done frightened things before and remained.',
      'Let my hands be slow and certain.',
      'Let my voice, when it comes, be lower than the fear.',
      'I go forward not because I am unafraid, but because I am here.',
    ].join('\n'),
    breathPatterns: [
      { inhale: 4, holdIn: 4, exhale: 6, holdOut: 0 },
      { inhale: 4, holdIn: 4, exhale: 8, holdOut: 0 },
    ],
    groundingActions: [
      'Take the first small step of the frightening thing within the next ten minutes.',
      'Write one sentence naming exactly what you are afraid of, in plain words.',
      'Name one frightening thing you already survived, and write the date beside it.',
      'Stand tall, drop your shoulders, and take five slow steps across the room.',
    ],
    silenceSeconds: { whisper: 15, ritual: 46, deep: 92 },
  },
  {
    id: 'guard-closed-hand',
    intent: 'guard',
    title: 'The Closed Hand',
    opening: 'Not every offering must be taken.',
    invocation: [
      'There is a thing being handed to me that I did not ask for:',
      'a mood, a blame, an argument dressed as concern.',
      'My hand closes. Gently, but it closes.',
      'I can refuse a burden without refusing the person.',
      'I can say no in a low voice and mean it entirely.',
      'What I do not take, I do not have to carry home.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 7, holdOut: 1 }],
    groundingActions: [
      'Write the words you will use to say no, and keep them to one sentence.',
      'Return one thing that was handed to you today: a task, a decision, a mood.',
      'Close your hand, hold it closed for a slow count of ten, then open it.',
      'Remove one commitment from tomorrow that was never truly yours.',
    ],
    silenceSeconds: { whisper: 13, ritual: 42, deep: 85 },
  },
  {
    id: 'guard-nightwatch',
    intent: 'guard',
    title: 'Nightwatch',
    opening: 'The dark is long, but it is not endless.',
    invocation: [
      'It is late, and the mind has begun to build its worst buildings.',
      'I will not live in them tonight.',
      'I set a watch: breath, weight, the cool edge of the room.',
      'Nothing must be solved before morning.',
      'Nothing decided at this hour is decided well.',
      'Let me hold the hours until light, and let the holding be enough.',
    ].join('\n'),
    breathPatterns: [
      { inhale: 4, holdIn: 2, exhale: 8, holdOut: 0 },
      { inhale: 4, holdIn: 0, exhale: 8, holdOut: 2 },
    ],
    groundingActions: [
      'Write tomorrow the single question you are trying to answer, and stop there.',
      "Put the phone face down, out of arm's reach, and lie back down.",
      'Drink a small glass of water and let the room stay dark.',
      'Name three things you can hear right now, then close your eyes.',
    ],
    silenceSeconds: { whisper: 18, ritual: 55, deep: 110 },
  },
  {
    id: 'guard-low-wall',
    intent: 'guard',
    title: 'The Low Wall',
    opening: 'Build no higher than you can maintain.',
    invocation: [
      'I have built walls before that cost more to keep than they ever saved.',
      'This one is low, and honest, and mine.',
      'It says: here is what I can give, and here is where the giving ends.',
      'It has a gate, and I know where the gate is.',
      'Let me defend without disappearing.',
      'Let me be safe and still reachable.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 6, holdOut: 2 }],
    groundingActions: [
      'Write down what you can give this week, and where it ends. Two lines.',
      'Send one short message that keeps a door open rather than closing it.',
      'Cancel one thing you agreed to while overextended.',
      'Identify the one person you will still make time for this week.',
    ],
    silenceSeconds: { whisper: 14, ritual: 44, deep: 86 },
  },
  {
    id: 'guard-answer-nothing',
    intent: 'guard',
    title: 'Answer Nothing',
    opening: 'Silence is also a reply.',
    invocation: [
      'There is a provocation waiting for my answer,',
      'and it was built carefully to receive one.',
      'I will not furnish it.',
      'Let the sentence I did not send stay unsent.',
      'Let the hour pass, and the heat pass with it.',
      'Restraint is not weakness. Tonight it is the harder and better thing.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 3, exhale: 7, holdOut: 0 }],
    groundingActions: [
      'Leave the message unanswered until tomorrow, and close the application.',
      'Write what you wanted to say on paper, then put the paper away.',
      'Mute the conversation for twenty-four hours.',
      'Do one useful, physical thing instead: dishes, a walk, a cleared surface.',
    ],
    silenceSeconds: { whisper: 16, ritual: 50, deep: 100 },
  },
  {
    id: 'guard-kept-room',
    intent: 'guard',
    title: 'The Kept Room',
    opening: 'Keep one room in yourself unentered.',
    invocation: [
      'There is a room in me that no argument has been given the key to.',
      'I go there now and find it as I left it: plain, swept, quiet.',
      'The day may have the rest of me. It may not have this.',
      'Let me return here whenever the noise learns my name.',
      'Let the door hold without hardening.',
      'I keep this room. It keeps me.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 4, exhale: 6, holdOut: 2 }],
    groundingActions: [
      'Spend two minutes somewhere quiet with nothing in your hands.',
      'Clear one small surface and leave it empty.',
      'Write one thing about yourself that today did not touch.',
      'Sit still for sixty seconds before you re-enter the noise.',
    ],
    silenceSeconds: { whisper: 17, ritual: 52, deep: 105 },
  },
  {
    id: 'guard-under-weight',
    intent: 'guard',
    title: 'Steady Under Weight',
    opening: 'Carry it the way stone carries.',
    invocation: [
      'The weight has not lessened, and I have stopped waiting for it to.',
      'So I will learn the carrying instead.',
      'Feet apart. Breath low. Shoulders down from the ears.',
      'Strength is not the absence of strain; it is strain, well distributed.',
      'Let me set it down when I can and lift it well when I must.',
      "I am still standing. That is the whole of today's work.",
    ].join('\n'),
    breathPatterns: [
      { inhale: 4, holdIn: 2, exhale: 6, holdOut: 0 },
      { inhale: 5, holdIn: 3, exhale: 7, holdOut: 0 },
    ],
    groundingActions: [
      'Ask one person for one specific piece of help today.',
      'Take the weight off for ten minutes: sit down, eyes closed, no phone.',
      'Write the one part of the load that someone else could carry.',
      'Eat something and drink a full glass of water before continuing.',
    ],
    silenceSeconds: { whisper: 15, ritual: 45, deep: 90 },
  },
  {
    id: 'guard-named-border',
    intent: 'guard',
    title: 'The Named Border',
    opening: 'A limit unspoken is a limit undefended.',
    invocation: [
      'I have expected others to find a line I never drew.',
      'Tonight I draw it, and I will say it aloud where it belongs.',
      'Not as accusation. As information.',
      'Here is what I can do. Here is where I stop.',
      'Let me say it once, clearly, and not apologise for the map.',
      'A named border is a kindness to everyone standing near it.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 6, holdOut: 2 }],
    groundingActions: [
      'Write the exact sentence you will say, then say it to one person today.',
      'Put your finishing time in the calendar and tell someone it is fixed.',
      'Name one limit to yourself in writing, dated.',
      'Send one message that states clearly what you will not be doing.',
    ],
    silenceSeconds: { whisper: 14, ritual: 43, deep: 87 },
  },
  {
    id: 'guard-cold-water',
    intent: 'guard',
    title: 'Cold Water',
    opening: 'Enter it before the mind can argue.',
    invocation: [
      'There is a cold thing waiting that I have been circling for days.',
      'The circling costs more than the cold ever will.',
      'I will step in, and the first shock will pass, as it always passes.',
      'Let me not rehearse it further.',
      'Let me move while the breath is still steady.',
      'Three, two, one — and then it is behind me.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 1, exhale: 6, holdOut: 1 }],
    groundingActions: [
      'Do the avoided thing now, in its smallest possible first step.',
      'Send the message you have been drafting in your head for a week.',
      'Wash your face in cold water and begin.',
      'Set a timer for five minutes and start the thing before it rings.',
    ],
    silenceSeconds: { whisper: 12, ritual: 40, deep: 80 },
  },
  {
    id: 'guard-not-carry',
    intent: 'guard',
    title: 'What I Will Not Carry',
    opening: 'Set down what was never yours to hold.',
    invocation: [
      'I have been carrying moods that were not mine,',
      'decisions made in rooms I was not in,',
      "and the weather of other people's difficult days.",
      'I set them down here, without ceremony and without blame.',
      "Let me be responsible for my own conduct and no one's temperament.",
      'My hands are needed for my own work. I take them back.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 0, exhale: 8, holdOut: 0 }],
    groundingActions: [
      'Write down one thing you have been blaming yourself for that was not yours.',
      'Put one object back where it belongs and leave the rest.',
      'Open your hands, palms up, for a slow count of ten.',
      'Remove yourself from one conversation that is not yours to resolve.',
    ],
    silenceSeconds: { whisper: 15, ritual: 47, deep: 94 },
  },
]
