import type { RitualDefinition } from './types'

/**
 * MEND — recovery, patience, emotional healing, restoration.
 *
 * These passages are deliberately unhurried. Nothing here promises repair
 * on a schedule.
 */
export const MEND_RITUALS: RitualDefinition[] = [
  {
    id: 'mend-convalescence',
    intent: 'mend',
    title: 'The Long Convalescence',
    opening: 'Healing keeps its own calendar.',
    invocation: [
      'I have been demanding a schedule from something that has never kept one.',
      'The mending will take the time the mending takes.',
      'I stop counting the days I am behind.',
      'Beneath the surface, in the dark, the work is already happening —',
      'quietly, without my supervision, and better without my impatience.',
      'Let me be a good place for the healing to happen in.',
    ].join('\n'),
    breathPatterns: [
      { inhale: 4, holdIn: 1, exhale: 6, holdOut: 0 },
      { inhale: 5, holdIn: 2, exhale: 7, holdOut: 1 },
    ],
    groundingActions: [
      'Remove one thing from tomorrow that you are not well enough to do.',
      'Drink a glass of water and sit down for five minutes.',
      'Write one honest line about how you actually are today.',
      'Go to bed thirty minutes earlier than you planned.',
    ],
    silenceSeconds: { whisper: 17, ritual: 52, deep: 105 },
  },
  {
    id: 'mend-knitting',
    intent: 'mend',
    title: 'What Is Knitting',
    opening: 'Beneath the surface, something is joining.',
    invocation: [
      'There is a seam in me that is not finished closing.',
      'It aches when I move too quickly, and I have been moving quickly.',
      'So: slower. Not stopped. Slower.',
      'What is knitting must be kept still enough to knit',
      'and used gently enough to remember its strength.',
      'Let me be neither reckless with it nor afraid of it.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 7, holdOut: 1 }],
    groundingActions: [
      'Do one gentle version of something you used to do fully.',
      'Stretch slowly for two minutes, stopping before anything hurts.',
      'Say no to one thing that would strain what is still healing.',
      'Eat something proper rather than something quick.',
    ],
    silenceSeconds: { whisper: 15, ritual: 48, deep: 96 },
  },
  {
    id: 'mend-kind-voice',
    intent: 'mend',
    title: 'The Kind Voice',
    opening: 'Use the voice you would use for someone you love.',
    invocation: [
      'I have spoken to myself all week in a voice I would never use on another.',
      'Sharp. Impatient. Certain of the worst reading.',
      'Let me change the voice, if not yet the facts.',
      'The facts are: I am tired, I am trying, and I have been here before and got through.',
      'Let me say that plainly, in a tone I could stand to hear.',
      'Kindness is not a reward for recovery. It is a condition of it.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 6, holdOut: 1 }],
    groundingActions: [
      'Write one sentence to yourself as you would write it to a friend.',
      'Say one true, generous thing about your own week, out loud.',
      'Do one small kind thing for yourself in the next ten minutes.',
      'Send one message you have been avoiding, kindly worded.',
    ],
    silenceSeconds: { whisper: 16, ritual: 50, deep: 100 },
  },
  {
    id: 'mend-slow-repair',
    intent: 'mend',
    title: 'Slow Repair',
    opening: 'A thing well mended is mended slowly.',
    invocation: [
      'I want this fixed today, and it will not be fixed today.',
      'The fast repair is the one that fails again in a month.',
      'So I will do the slow one:',
      'a small honest step, and then rest, and then another.',
      'Let me not tear the work open to inspect it.',
      'Let it hold. Let it set. Let it be quietly becoming whole.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 8, holdOut: 0 }],
    groundingActions: [
      'Do one small repairing step, then deliberately stop for the day.',
      'Write down what you will not try to fix this week.',
      'Put one object back where it belongs.',
      'Rest for ten minutes without calling it wasted time.',
    ],
    silenceSeconds: { whisper: 15, ritual: 46, deep: 94 },
  },
  {
    id: 'mend-mended-bowl',
    intent: 'mend',
    title: 'The Mended Bowl',
    opening: 'What is repaired keeps the line of its repair.',
    invocation: [
      'I will not pretend the break did not happen.',
      'The line will show. It is allowed to show.',
      'A mended thing is not a lesser thing; it is a thing that has been cared for.',
      'I have been cared for, including by myself, including tonight.',
      'Let the seam be visible and strong.',
      'I am not trying to become someone who was never broken.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 3, exhale: 7, holdOut: 0 }],
    groundingActions: [
      'Write one sentence about something difficult that changed you usefully.',
      'Repair one small broken thing in your home.',
      'Tell one person a true thing about a hard period you came through.',
      'Look at one scar or old difficulty without arguing with it.',
    ],
    silenceSeconds: { whisper: 16, ritual: 50, deep: 102 },
  },
  {
    id: 'mend-grief-room',
    intent: 'mend',
    title: 'Grief, Given Room',
    opening: 'Give it the room it is asking for.',
    invocation: [
      'There is a grief in the house that I keep asking to be quieter.',
      'Tonight I give it a chair.',
      'It does not need to be solved, argued with, or hurried out of the door.',
      'It needs to be sat with, and then it eases —',
      'not because I fixed it, but because it was finally allowed to be here.',
      'Let me stay in the room a few minutes longer than is comfortable.',
    ].join('\n'),
    breathPatterns: [
      { inhale: 4, holdIn: 1, exhale: 7, holdOut: 0 },
      { inhale: 4, holdIn: 2, exhale: 8, holdOut: 1 },
    ],
    groundingActions: [
      'Sit still for sixty seconds and let whatever is there be there.',
      'Write the name of what you are grieving, and nothing else.',
      'Tell one person that you are having a hard week.',
      'Drink a glass of water and let the evening be slow.',
    ],
    silenceSeconds: { whisper: 20, ritual: 60, deep: 120 },
  },
  {
    id: 'mend-returning-strength',
    intent: 'mend',
    title: 'The Returning Strength',
    opening: 'Strength returns quietly, and later than hoped.',
    invocation: [
      'I have compared myself all week to who I was before.',
      'That comparison is a debt I keep choosing to owe.',
      'Today has its own capacity, and it is not nothing.',
      'Let me spend it well and not overdraw it.',
      'The strength is coming back in the way strength comes back:',
      'unevenly, unannounced, and mostly while I am not watching for it.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 6, holdOut: 2 }],
    groundingActions: [
      'Do one thing at sixty percent of what you would once have attempted.',
      'Write down one thing you can do now that you could not last month.',
      'Take five slow steps outside.',
      'Stop one activity while you still have something left.',
    ],
    silenceSeconds: { whisper: 14, ritual: 45, deep: 92 },
  },
  {
    id: 'mend-forgive-body',
    intent: 'mend',
    title: 'Forgive The Body',
    opening: 'The body has been doing its work without thanks.',
    invocation: [
      'I have been treating the body as an obstacle to my plans.',
      'It has kept me alive the entire time, without instruction.',
      'It is tired because it has been carrying something heavy.',
      'Let me stop arguing with it and listen to what it is asking:',
      'water, sleep, movement, a little light, less of what hurts it.',
      'Simple requests, honestly made. Let me answer one of them tonight.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 7, holdOut: 0 }],
    groundingActions: [
      'Drink a full glass of water now.',
      'Eat something with actual nutrition in it.',
      'Step outside briefly, even for two minutes.',
      'Go to bed at a time you would recommend to someone you care about.',
    ],
    silenceSeconds: { whisper: 15, ritual: 47, deep: 95 },
  },
  {
    id: 'mend-old-wound',
    intent: 'mend',
    title: 'The Old Wound, Aired',
    opening: 'What is covered too long does not heal well.',
    invocation: [
      'There is an old thing I have kept sealed because opening it hurt.',
      'Sealed, it has not healed; it has only waited.',
      'I do not open all of it tonight. I open a corner.',
      'I look at it plainly, without the story I usually tell about it.',
      'Let the air reach it. Let it sting briefly, and then begin.',
      'Some things only close after they are honestly seen.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 3, exhale: 7, holdOut: 1 }],
    groundingActions: [
      'Write three plain sentences about the old thing, without judgement.',
      'Tell one trusted person one true sentence about it.',
      'Look at one photograph or object connected to it, calmly.',
      'Write down what you would need in order to set it down.',
    ],
    silenceSeconds: { whisper: 18, ritual: 55, deep: 110 },
  },
  {
    id: 'mend-not-yet-nearer',
    intent: 'mend',
    title: 'Not Yet, But Nearer',
    opening: 'Not healed. Nearer.',
    invocation: [
      'I am not well yet, and I am tired of pretending otherwise for other people.',
      'But I am nearer than I was in the worst week.',
      'Nearer is a real distance. It counts.',
      'Let me measure from the bottom rather than from the summit.',
      'Let me say, honestly: not yet, but nearer.',
      'That sentence is true, and it is enough to go on with.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 6, holdOut: 1 }],
    groundingActions: [
      'Write down one way this month is better than the worst one.',
      'Answer one person honestly when they ask how you are.',
      'Do one thing today that the worst week made impossible.',
      'Sit still for sixty seconds and notice that you are still here.',
    ],
    silenceSeconds: { whisper: 14, ritual: 44, deep: 90 },
  },
  {
    id: 'mend-tended-fire',
    intent: 'mend',
    title: 'The Tended Fire',
    opening: 'Keep the small fire. It is enough for tonight.',
    invocation: [
      'There is not much heat in me tonight, and I will not fake a blaze.',
      'But there is a small fire, and small fires are kept by attending to them:',
      'a little fuel, a little air, no dramatic gestures.',
      'Let me do the ordinary tending — eat, drink, sleep, speak to one person.',
      'Warmth returns to a room slowly and then all at once.',
      'Tonight I only have to keep it lit.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 1, exhale: 6, holdOut: 1 }],
    groundingActions: [
      'Send one message to someone who is easy to talk to.',
      'Make something warm to drink and finish it before doing anything else.',
      'Do the smallest useful task in the house and stop there.',
      'Turn on one warm light and turn off the overhead one.',
    ],
    silenceSeconds: { whisper: 16, ritual: 48, deep: 98 },
  },
  {
    id: 'mend-as-to-a-friend',
    intent: 'mend',
    title: 'As To A Friend',
    opening: 'Say to yourself what you would say to them.',
    invocation: [
      'If a friend told me exactly what I am telling myself,',
      'I would not agree with a word of the verdict.',
      'I would say: you were doing your best with what you had.',
      'I would say: this is hard, and you are not failing at it, you are inside it.',
      'Let me offer myself the same account, and believe it for one minute.',
      'The generosity I extend so easily outward can be turned around.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 6, holdOut: 2 }],
    groundingActions: [
      'Write the message you would send a friend in your situation, addressed to yourself.',
      'Drop one accusation you have been repeating about yourself.',
      'Tell one person something true and unflattering, and let them be kind about it.',
      'Do one thing you would tell a friend to do: eat, rest, or step outside.',
    ],
    silenceSeconds: { whisper: 15, ritual: 46, deep: 93 },
  },
  {
    id: 'mend-rest-is-work',
    intent: 'mend',
    title: 'Rest Is Work',
    opening: 'Rest is not the absence of the work. It is part of it.',
    invocation: [
      'I have treated rest as the thing I do when the work is finished,',
      'and the work is never finished, so I have not rested.',
      'Let me correct the order.',
      'Recovery is not idleness; it is the half of effort that makes effort possible.',
      'Let me stop now, deliberately, and not call it laziness.',
      'This pause is not stolen. It is required.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 0, exhale: 8, holdOut: 2 }],
    groundingActions: [
      'Stop working now, at a point that is not a natural ending.',
      'Put one rest period into tomorrow and treat it as an appointment.',
      'Lie down for ten minutes with a timer set.',
      'Close every tab and leave the desk.',
    ],
    silenceSeconds: { whisper: 18, ritual: 54, deep: 108 },
  },
]
