import type { RitualDefinition } from './types'

/**
 * RESOLVE — discipline, commitment, focus, finishing something difficult.
 *
 * Squarer breath patterns: this set is about holding a line rather than
 * softening one.
 */
export const RESOLVE_RITUALS: RitualDefinition[] = [
  {
    id: 'resolve-single-axis',
    intent: 'resolve',
    title: 'The Single Axis',
    opening: 'Let everything align to one line.',
    invocation: [
      'I have been pulled in six directions and moved in none.',
      'Tonight there is one axis, and everything else is set aside without apology.',
      'Not forever. For this stretch.',
      'Let the scattered filings turn and point the same way.',
      'Let the effort be narrow enough to actually cut.',
      'One line, held long enough, goes through almost anything.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 4, exhale: 4, holdOut: 4 }],
    groundingActions: [
      'Write the one thing on paper and put it where you will work.',
      'Close every tab that is not the one thing.',
      'Set a timer for twenty-five minutes and work on it alone.',
      'Remove one competing commitment from this week.',
    ],
    silenceSeconds: { whisper: 14, ritual: 45, deep: 90 },
  },
  {
    id: 'resolve-begin-badly',
    intent: 'resolve',
    title: 'Begin Badly',
    opening: 'Begin badly rather than not at all.',
    invocation: [
      'I have been waiting for the right conditions, and they will not come.',
      'The good version does not exist yet because no version exists yet.',
      'So I will make a poor first one, quickly, without ceremony.',
      'Let it be clumsy. Let it be short. Let it exist.',
      'A bad beginning can be improved. A perfect intention cannot.',
      'The first ten minutes are the whole battle. I take them now.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 5, holdOut: 1 }],
    groundingActions: [
      'Write the worst possible first draft of one paragraph, right now.',
      'Set a timer for ten minutes and start before it finishes counting down.',
      'Open the file you have been avoiding and change one line.',
      'Do the first physical step: open the document, put on the shoes, make the call.',
    ],
    silenceSeconds: { whisper: 12, ritual: 40, deep: 80 },
  },
  {
    id: 'resolve-kept-word',
    intent: 'resolve',
    title: 'The Kept Word',
    opening: 'Keep the promise you made to yourself.',
    invocation: [
      'I keep my word to almost everyone and break it quietly to myself,',
      'and then wonder why I do not trust my own intentions.',
      'Tonight I keep one — a small one, chosen because I will actually keep it.',
      'Let it be specific, modest, and finished before I sleep.',
      'Self-trust is not a feeling; it is a record of kept promises.',
      'I add one line to the record tonight.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 4, exhale: 6, holdOut: 2 }],
    groundingActions: [
      'Name one small promise to yourself and complete it before sleeping.',
      'Write down the promise, with a time attached.',
      'Do the thing you told yourself you would do this morning.',
      'Cancel one promise you know you will not keep, honestly.',
    ],
    silenceSeconds: { whisper: 15, ritual: 46, deep: 92 },
  },
  {
    id: 'resolve-finish-one',
    intent: 'resolve',
    title: 'Finish The One Thing',
    opening: 'Finishing is a different skill from starting.',
    invocation: [
      'I have begun many things and completed few, and the unfinished ones cost the most.',
      'Tonight, no new beginnings.',
      'One thing, already started, carried to the end — even a small end.',
      'Let me resist the pleasant rush of starting something else.',
      'Let me stay with the dull final stretch where the work is actually done.',
      'Finished is a quality that nothing unfinished has.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 4, exhale: 5, holdOut: 3 }],
    groundingActions: [
      'Complete one unfinished task before opening another.',
      'Pick the oldest unfinished thing on your list and end it tonight.',
      'Spend fifteen minutes only on the final stretch of something started.',
      'Write down which one thing you are finishing, and cross nothing else off.',
    ],
    silenceSeconds: { whisper: 13, ritual: 42, deep: 86 },
  },
  {
    id: 'resolve-hard-hour',
    intent: 'resolve',
    title: 'The Hard Hour',
    opening: 'One hour, given completely.',
    invocation: [
      'Not a life of discipline. One hour.',
      'Phone away. Door closed. One task, plainly named before I begin.',
      'When it becomes uncomfortable — and it will, at about the twelfth minute —',
      'I will stay, because that discomfort is the work and not a signal to stop.',
      'Let me spend one honest hour and not grade it afterwards.',
      'Hours like this are how difficult things eventually fall.',
    ].join('\n'),
    breathPatterns: [
      { inhale: 4, holdIn: 4, exhale: 4, holdOut: 4 },
      { inhale: 5, holdIn: 3, exhale: 5, holdOut: 3 },
    ],
    groundingActions: [
      'Put the phone in another room and begin one hour of work.',
      'Name the single task out loud before you start.',
      'Close the door and set a timer.',
      'Work until the timer ends, even badly.',
    ],
    silenceSeconds: { whisper: 12, ritual: 41, deep: 82 },
  },
  {
    id: 'resolve-no-negotiation',
    intent: 'resolve',
    title: 'No Negotiation',
    opening: 'The decision was made. This is not the hour to reopen it.',
    invocation: [
      'I decided this when I was clear-headed, and now, tired, I am reopening the case.',
      'The tired mind is a poor advocate and an excellent negotiator.',
      'It does not get a vote tonight.',
      'Let the earlier decision stand without a new hearing.',
      'I do not need to want to. I only need to do it.',
      'The negotiation is closed. The action is open.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 4, exhale: 4, holdOut: 4 }],
    groundingActions: [
      'Do the thing you already decided on, without revisiting the reasoning.',
      'Write down the decision and the date you made it.',
      'Remove the option you already ruled out from your list.',
      'Start the task within the next two minutes.',
    ],
    silenceSeconds: { whisper: 13, ritual: 43, deep: 85 },
  },
  {
    id: 'resolve-small-vow',
    intent: 'resolve',
    title: 'The Small Vow',
    opening: 'Swear something small enough to be true.',
    invocation: [
      'Grand resolutions have failed me because they were never promises, only moods.',
      'So: something small. Something certain.',
      'One page. One set. One conversation. One clean surface.',
      'Let the vow be so modest that failing it would be absurd —',
      'and then let me keep it tonight, without renegotiating the size.',
      'Small vows kept build what large vows only describe.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 3, exhale: 5, holdOut: 2 }],
    groundingActions: [
      'Name one thing you will do in the next thirty minutes, and do it.',
      'Write the smallest useful version of your goal and complete it.',
      "Reduce tomorrow's commitment until it is certain, then keep it.",
      'Do one repetition of the thing you have been meaning to begin.',
    ],
    silenceSeconds: { whisper: 14, ritual: 44, deep: 88 },
  },
  {
    id: 'resolve-return-to-bench',
    intent: 'resolve',
    title: 'Return To The Bench',
    opening: 'Return without a speech about having left.',
    invocation: [
      'I stopped, and then I made the stopping mean something about my character,',
      'and the meaning kept me away longer than the stopping ever did.',
      'Let me skip the verdict and simply return to the bench.',
      'No apology to myself. No accounting of lost days.',
      'The work does not remember the gap. It only knows whether I am here now.',
      'I am here now. That is the entire ceremony.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 3, exhale: 6, holdOut: 1 }],
    groundingActions: [
      'Open the abandoned project and work on it for five minutes.',
      'Do one repetition of the practice you stopped, without comment.',
      'Delete the running tally of days you missed.',
      "Put tomorrow's session in the calendar before you close the laptop.",
    ],
    silenceSeconds: { whisper: 14, ritual: 45, deep: 91 },
  },
  {
    id: 'resolve-through-not-around',
    intent: 'resolve',
    title: 'Through, Not Around',
    opening: 'The way out is the way through.',
    invocation: [
      'I have found many routes around this, and every one has been longer.',
      'Avoidance is not a shortcut; it is a payment plan with interest.',
      'Let me go at it directly, in the plainest possible way,',
      'starting with the part I understand least, which is where the fear lives.',
      'Let the first cut be into the hard middle rather than the easy edge.',
      'Through is shorter. It has always been shorter.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 4, exhale: 5, holdOut: 2 }],
    groundingActions: [
      'Start with the hardest part of the task rather than the easiest.',
      'Send the message you have been avoiding.',
      'Write down what you have been going around, and name the direct route.',
      'Spend ten minutes on the part you understand least.',
    ],
    silenceSeconds: { whisper: 13, ritual: 42, deep: 84 },
  },
  {
    id: 'resolve-chosen-difficulty',
    intent: 'resolve',
    title: 'The Chosen Difficulty',
    opening: 'Choose the difficulty and it stops being a burden.',
    invocation: [
      'This is hard, and I have treated that as evidence something is wrong.',
      'Nothing is wrong. Hard is the correct texture of work worth doing.',
      'I chose this. Let me choose it again, deliberately, now.',
      'Let the difficulty be a fact I work with rather than an injustice I protest.',
      'Resentment doubles the weight of everything it touches.',
      'Chosen, the same task weighs half as much.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 4, exhale: 4, holdOut: 4 }],
    groundingActions: [
      'Write one sentence about why you chose this, and keep it visible.',
      'Do the next hard step without complaining about it, even internally.',
      'Write down what finishing this would make possible.',
      'Begin the difficult task within the next five minutes.',
    ],
    silenceSeconds: { whisper: 14, ritual: 44, deep: 89 },
  },
  {
    id: 'resolve-show-up',
    intent: 'resolve',
    title: 'Show Up Anyway',
    opening: 'Motivation is not required. Attendance is.',
    invocation: [
      'I do not feel like it, and I have been waiting to feel like it since Tuesday.',
      'The feeling follows the action; it has never once led.',
      'So I go, unmotivated, and begin badly, and after ten minutes something turns over.',
      'Let me not consult my enthusiasm before starting.',
      'Let attendance be unconditional and the mood be optional.',
      'Show up. The work gets done either way.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 5, holdOut: 2 }],
    groundingActions: [
      'Go to the place where the work happens, even without enthusiasm.',
      'Do five minutes of it and allow yourself to stop afterwards.',
      'Put on the clothes or open the tool the work requires.',
      'Take five slow steps toward the thing and begin.',
    ],
    silenceSeconds: { whisper: 12, ritual: 40, deep: 81 },
  },
  {
    id: 'resolve-last-ten-percent',
    intent: 'resolve',
    title: 'The Last Ten Percent',
    opening: 'The end is the steepest part. Expect it.',
    invocation: [
      'It is nearly finished, and this is exactly where I usually leave things —',
      'close enough to feel done, far enough to remain undone forever.',
      'The last stretch is tedious, unglamorous, and entirely necessary.',
      'Let me stay for the tidying, the checking, the small dull corrections.',
      'Let me not abandon it within sight of the end.',
      'Ninety percent is not a finished thing. It is a heavier unfinished one.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 4, exhale: 6, holdOut: 2 }],
    groundingActions: [
      'Spend twenty minutes on the final unglamorous details.',
      'List everything still between you and finished, then do the top item.',
      'Send it, publish it, or hand it over today.',
      'Do the checking step you have been skipping.',
    ],
    silenceSeconds: { whisper: 13, ritual: 43, deep: 87 },
  },
  {
    id: 'resolve-line-in-calendar',
    intent: 'resolve',
    title: 'The Line In The Calendar',
    opening: 'An intention without an hour is a wish.',
    invocation: [
      'I have intended this for a month, and intention has produced nothing.',
      'It has no hour, so it has no existence.',
      'Tonight I give it one: a specific time, on a specific day, written where I will see it.',
      'Let it become an appointment rather than a hope.',
      'Let me defend that hour as I would defend one made with another person.',
      'What is scheduled happens. What is merely wanted waits forever.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 3, exhale: 5, holdOut: 3 }],
    groundingActions: [
      'Put the task in the calendar now, with a start time and an end time.',
      'Tell one person when you are going to do it.',
      'Set an alarm for the hour you have chosen.',
      'Write one sentence about what matters next, with a date beside it.',
    ],
    silenceSeconds: { whisper: 14, ritual: 45, deep: 90 },
  },
]
