import type { RitualDefinition } from './types'

/**
 * SEEK — insight, reflection, difficult decisions, perspective.
 *
 * Balanced breath patterns: this set is neither settling nor releasing,
 * it is holding a question steady enough to look at.
 */
export const SEEK_RITUALS: RitualDefinition[] = [
  {
    id: 'seek-honest-question',
    intent: 'seek',
    title: 'The Honest Question',
    opening: 'Ask the question you have been avoiding.',
    invocation: [
      'I have been asking easy questions and receiving useless answers.',
      'Beneath them is one I have been walking around for weeks.',
      'I will say it plainly now, in this room, where no one is listening.',
      'No defence. No preparing the answer before it arrives.',
      'Let the question stand in the middle of the floor.',
      'An honest question, held long enough, begins to answer itself.',
    ].join('\n'),
    breathPatterns: [{ inhale: 5, holdIn: 3, exhale: 5, holdOut: 1 }],
    groundingActions: [
      'Write the real question down in one sentence, and leave it where you will see it.',
      'Ask one person the question you have been avoiding asking.',
      'Sit still for sixty seconds with the question and no answer.',
      'Write one sentence about what matters next.',
    ],
    silenceSeconds: { whisper: 18, ritual: 55, deep: 110 },
  },
  {
    id: 'seek-wider-view',
    intent: 'seek',
    title: 'The Wider View',
    opening: 'Step back until the shape appears.',
    invocation: [
      'I have been standing too close to see the shape of it.',
      'So: back. Further back.',
      'From here the urgent thing is one feature of a longer landscape.',
      'Some of what looked like collapse is only weather.',
      'Let me look at the whole terrain before choosing a direction.',
      'Perspective is not comfort. It is accuracy, and accuracy is what I need.',
    ].join('\n'),
    breathPatterns: [{ inhale: 5, holdIn: 2, exhale: 6, holdOut: 1 }],
    groundingActions: [
      'Write down what this will look like in one year, in three sentences.',
      'Step outside and look at something far away.',
      'Tell one person the whole situation from the beginning.',
      'Write down one thing that seemed enormous last year and no longer is.',
    ],
    silenceSeconds: { whisper: 16, ritual: 50, deep: 100 },
  },
  {
    id: 'seek-what-not-saying',
    intent: 'seek',
    title: 'What I Am Not Saying',
    opening: 'Listen for the thing beneath the words.',
    invocation: [
      'There is something I have not said, and its absence has shaped everything I have said.',
      'I feel its outline in what I avoid, in what makes me change the subject.',
      'Let me approach it slowly and name it here first, where it costs nothing.',
      'It may be small. It may be the whole matter.',
      'Let me say it once, silently, in full.',
      'What is named can be worked with. What is unnamed works on me instead.',
    ].join('\n'),
    breathPatterns: [{ inhale: 5, holdIn: 3, exhale: 6, holdOut: 0 }],
    groundingActions: [
      'Write the unsaid thing down in plain words and keep the paper.',
      'Say it out loud once, alone, and hear how it sounds.',
      'Send one message you have been avoiding.',
      'Tell one trusted person the part you have been leaving out.',
    ],
    silenceSeconds: { whisper: 17, ritual: 54, deep: 108 },
  },
  {
    id: 'seek-two-roads',
    intent: 'seek',
    title: 'Two Roads, Weighed',
    opening: 'Hold both fully before choosing either.',
    invocation: [
      'There are two ways, and I have been living in the corridor between them.',
      'The corridor is the most expensive place to stand.',
      'Let me enter the first fully — a year of it, its ordinary Tuesdays, not its brochure.',
      'Then the second, the same way.',
      'The body knows something the argument does not; let me notice which one loosens the chest.',
      'Then let me choose, and let the other road close cleanly behind me.',
    ].join('\n'),
    breathPatterns: [
      { inhale: 5, holdIn: 5, exhale: 5, holdOut: 0 },
      { inhale: 5, holdIn: 3, exhale: 7, holdOut: 0 },
    ],
    groundingActions: [
      'Write both options at the top of one page and give each five honest lines.',
      'Set a date by which the decision will be made, and write it down.',
      'Tell one person which way you are actually leaning.',
      'Take one small reversible step down one of the roads today.',
    ],
    silenceSeconds: { whisper: 19, ritual: 58, deep: 115 },
  },
  {
    id: 'seek-ten-year-look',
    intent: 'seek',
    title: 'The Ten Year Look',
    opening: 'Ask what will still matter.',
    invocation: [
      'Very little of what occupied me today will survive ten years.',
      'Some of it will not survive the week.',
      'But one or two things will, and they have not been getting my attention.',
      'Let me see this decision from further along the road.',
      'What would the person I am becoming want me to protect tonight?',
      'Let me spend these hours as though they belong to that person, because they do.',
    ].join('\n'),
    breathPatterns: [{ inhale: 5, holdIn: 2, exhale: 7, holdOut: 1 }],
    groundingActions: [
      'Write down the one thing from this year that will still matter in ten.',
      'Give fifteen minutes tonight to the thing that lasts.',
      'Remove one thing from tomorrow that will not matter next month.',
      'Send one message to a person you want to still know in ten years.',
    ],
    silenceSeconds: { whisper: 17, ritual: 52, deep: 105 },
  },
  {
    id: 'seek-quiet-counsel',
    intent: 'seek',
    title: 'The Quiet Counsel',
    opening: 'The quietest voice is often the one that knows.',
    invocation: [
      'There are many voices in this, and the loudest are fear and pride,',
      'and they have been talking over something smaller.',
      'Let the loud ones finish. They will, if I stop arguing with them.',
      'Underneath is a quiet observation that has been true for some time.',
      'Let me be still enough to hear it stated once, without decoration.',
      'I have usually known. I have not always listened.',
    ].join('\n'),
    breathPatterns: [{ inhale: 5, holdIn: 4, exhale: 6, holdOut: 1 }],
    groundingActions: [
      'Write the quiet observation down before it is talked over again.',
      'Sit still for sixty seconds without deciding anything.',
      'Say the quiet thing out loud once, to yourself.',
      'Act on the quiet observation in one small way today.',
    ],
    silenceSeconds: { whisper: 20, ritual: 60, deep: 120 },
  },
  {
    id: 'seek-beneath-first-answer',
    intent: 'seek',
    title: 'Beneath The First Answer',
    opening: 'The first answer is rarely the true one.',
    invocation: [
      'The first answer arrived quickly, because it is the one I have used before.',
      'It is not wrong. It is only shallow.',
      'Let me ask again, of the same question, and wait longer this time.',
      'The second answer is more honest. The third usually costs something.',
      'Let me go as far as the third and look at what it asks of me.',
      'Depth is only patience applied to a question.',
    ].join('\n'),
    breathPatterns: [{ inhale: 5, holdIn: 3, exhale: 6, holdOut: 2 }],
    groundingActions: [
      'Ask yourself the same question three times in writing, and keep the third answer.',
      'Sit with the question for two minutes before answering it.',
      'Write one sentence about what the honest answer would require.',
      'Tell one person the third answer rather than the first.',
    ],
    silenceSeconds: { whisper: 18, ritual: 56, deep: 112 },
  },
  {
    id: 'seek-what-would-i-advise',
    intent: 'seek',
    title: 'What Would I Advise',
    opening: 'Give yourself the counsel you would give another.',
    invocation: [
      'If this exact situation belonged to someone I respected,',
      'I would see it clearly within a minute.',
      'I would not call them foolish. I would not tell them to wait forever.',
      'I would name the one thing they were avoiding and ask what it would take.',
      'Let me put my own case before that clearer person and hear the answer.',
      'I already have the judgement. I have been withholding it from myself.',
    ].join('\n'),
    breathPatterns: [{ inhale: 5, holdIn: 2, exhale: 6, holdOut: 0 }],
    groundingActions: [
      'Write the advice you would give a friend in your position, in three lines.',
      'Do the first step of your own advice today.',
      'Tell one person what you would tell them if it were theirs.',
      'Write one sentence naming the thing you are avoiding.',
    ],
    silenceSeconds: { whisper: 16, ritual: 49, deep: 98 },
  },
  {
    id: 'seek-unwelcome-truth',
    intent: 'seek',
    title: 'The Unwelcome Truth',
    opening: 'Some truths arrive without comfort. Receive them anyway.',
    invocation: [
      'There is something true here that I would prefer were not.',
      'I have spent effort keeping it slightly out of focus, and the effort is exhausting.',
      'Let me look at it directly for the length of this silence.',
      'It does not become worse by being seen. It becomes finite.',
      'Let me stop paying the cost of not-knowing what I already know.',
      'A truth, once received, stops demanding and begins to instruct.',
    ].join('\n'),
    breathPatterns: [{ inhale: 5, holdIn: 4, exhale: 6, holdOut: 0 }],
    groundingActions: [
      'Write the unwelcome truth in one sentence and read it back once.',
      'Tell one trusted person the thing you have not been admitting.',
      'Write down one thing that changes now that you have admitted it.',
      'Take one small action that assumes the truth is true.',
    ],
    silenceSeconds: { whisper: 19, ritual: 58, deep: 116 },
  },
  {
    id: 'seek-shape-of-problem',
    intent: 'seek',
    title: 'The Shape Of The Problem',
    opening: 'Describe it accurately before trying to solve it.',
    invocation: [
      'I have been solving the wrong problem energetically.',
      'Before another plan, let me describe the actual shape:',
      'what is fixed, what is movable, what is only assumed to be fixed.',
      'Most walls in this are assumptions wearing the costume of stone.',
      'Let me test one of them tonight, gently.',
      'A well-described problem is already half answered.',
    ].join('\n'),
    breathPatterns: [{ inhale: 5, holdIn: 3, exhale: 5, holdOut: 2 }],
    groundingActions: [
      'Write the problem in one sentence, then list what is genuinely fixed.',
      'Test one assumption today by asking someone directly.',
      'Draw the situation on paper rather than describing it.',
      'Write one sentence about what you actually want to happen.',
    ],
    silenceSeconds: { whisper: 15, ritual: 48, deep: 96 },
  },
  {
    id: 'seek-ask-better',
    intent: 'seek',
    title: 'Ask Better',
    opening: 'Change the question and the answers change.',
    invocation: [
      'Why is this happening to me has produced nothing in a month of asking.',
      'It is a question shaped to have no answer.',
      'Let me exchange it: what is one thing here I can influence?',
      'What would make tomorrow slightly more workable?',
      'Let the question be smaller, more specific, and answerable.',
      'Better questions are the cheapest available improvement.',
    ].join('\n'),
    breathPatterns: [{ inhale: 5, holdIn: 2, exhale: 6, holdOut: 1 }],
    groundingActions: [
      'Identify one thing you can control right now, and do it.',
      'Rewrite your worry as a question that has an answer.',
      'Write one sentence naming what would make tomorrow easier.',
      'Ask one person a better question than you asked them last time.',
    ],
    silenceSeconds: { whisper: 14, ritual: 46, deep: 92 },
  },
  {
    id: 'seek-longer-arc',
    intent: 'seek',
    title: 'The Longer Arc',
    opening: 'Read the chapter, not the sentence.',
    invocation: [
      'I have been judging a long story by its most recent paragraph.',
      'The paragraph is poor. The story is not the paragraph.',
      'Let me look back far enough to see the arc:',
      'what has changed, what I survived, what I now do easily that once undid me.',
      "Let me include that evidence in tonight's assessment.",
      'The arc is longer and better than the mood suggests.',
    ].join('\n'),
    breathPatterns: [{ inhale: 5, holdIn: 2, exhale: 7, holdOut: 0 }],
    groundingActions: [
      'Write down three things you can do now that you could not do three years ago.',
      'Read something you wrote a year ago.',
      'Write one sentence describing the last five years as a single arc.',
      'Tell one person about a difficulty you came through.',
    ],
    silenceSeconds: { whisper: 16, ritual: 51, deep: 102 },
  },
  {
    id: 'seek-what-at-stake',
    intent: 'seek',
    title: 'What Is Actually At Stake',
    opening: 'Name the real stake, not the imagined one.',
    invocation: [
      'The fear has told me that everything is at risk.',
      'Let me check the claim.',
      'What is truly at stake here: not my life, not my worth, not everything.',
      'Something real, and smaller, and survivable.',
      'Let me name it exactly, and notice how much lighter the exact version is.',
      'Precision reduces dread more reliably than reassurance ever has.',
    ].join('\n'),
    breathPatterns: [{ inhale: 5, holdIn: 3, exhale: 6, holdOut: 1 }],
    groundingActions: [
      'Write down the worst realistic outcome, and then what you would do next.',
      'Write one sentence naming what is genuinely at stake.',
      'Tell one person the specific thing you are afraid of losing.',
      'Identify one thing that is not at risk, and write it down.',
    ],
    silenceSeconds: { whisper: 17, ritual: 53, deep: 107 },
  },
]
