import type { RitualDefinition } from './types'

/**
 * STILL — calm, grounding, slowing mental noise, presence.
 *
 * The breath patterns in this set lengthen as they go: each ritual is
 * written to decelerate rather than to arrive anywhere.
 */
export const STILL_RITUALS: RitualDefinition[] = [
  {
    id: 'still-settling',
    intent: 'still',
    title: 'The Settling',
    opening: 'Let the water be still and the sediment will find the floor.',
    invocation: [
      'I have been stirred all day, and everything in me is suspended.',
      'I will not try to clear the water by reaching into it.',
      'I will only stop moving.',
      'The heavy things will find the floor on their own.',
      'Give it a minute. Give it two.',
      'Clarity is not something I make. It is what remains when I am still.',
    ].join('\n'),
    breathPatterns: [
      { inhale: 4, holdIn: 2, exhale: 6, holdOut: 0 },
      { inhale: 5, holdIn: 2, exhale: 7, holdOut: 1 },
    ],
    groundingActions: [
      'Sit still for sixty seconds with your hands open on your knees.',
      'Drink a glass of water slowly, without doing anything else.',
      'Put one object back where it belongs, then stop.',
      'Look out of a window at something further than ten metres away.',
    ],
    silenceSeconds: { whisper: 18, ritual: 55, deep: 110 },
  },
  {
    id: 'still-one-thing',
    intent: 'still',
    title: 'One Thing',
    opening: 'The mind holds one thing well and many things badly.',
    invocation: [
      'I have been carrying six days at once and living in none of them.',
      'So: one thing.',
      'This breath, which is the only one available.',
      'This room, which is the only one I am in.',
      'This hour, which is not yet spent.',
      'Let everything else keep its place in the line. It will still be there.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 6, holdOut: 2 }],
    groundingActions: [
      'Close every tab except the one you actually need.',
      'Write the single next action on a piece of paper and do only that.',
      'Finish one unfinished task before opening another.',
      'Put the phone in a different room for the next thirty minutes.',
    ],
    silenceSeconds: { whisper: 15, ritual: 48, deep: 96 },
  },
  {
    id: 'still-weight-of-chair',
    intent: 'still',
    title: 'The Weight Of The Chair',
    opening: 'Let the ground do the holding.',
    invocation: [
      'I have been holding myself up all day as though the floor might not.',
      'The floor will.',
      'I give my weight to the chair, and the chair gives it to the ground,',
      'and the ground asks nothing of me in return.',
      'Let the shoulders come down. Let the jaw come loose.',
      'There is nothing here to brace against.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 0, exhale: 8, holdOut: 0 }],
    groundingActions: [
      'Sit down properly and let your full weight rest for one minute.',
      'Unclench your jaw and drop your shoulders, deliberately, three times.',
      'Lie on the floor for two minutes with your eyes closed.',
      'Take five slow steps, feeling each foot land.',
    ],
    silenceSeconds: { whisper: 16, ritual: 50, deep: 100 },
  },
  {
    id: 'still-slow-water',
    intent: 'still',
    title: 'Slow Water',
    opening: 'Move as water moves in a wide place.',
    invocation: [
      'Speed has become a habit rather than a need.',
      'I have hurried through hours that asked nothing of me.',
      'Let this breath be slower than the last.',
      'Let the next be slower still.',
      'There is no prize for arriving early at the end of an evening.',
      'The water does not stop; it stops rushing.',
    ].join('\n'),
    breathPatterns: [
      { inhale: 4, holdIn: 1, exhale: 7, holdOut: 0 },
      { inhale: 5, holdIn: 2, exhale: 8, holdOut: 1 },
    ],
    groundingActions: [
      'Do the next small task at half your usual speed, on purpose.',
      'Walk to another room without hurrying, and notice that nothing breaks.',
      'Eat or drink something slowly enough to actually taste it.',
      'Take five slow steps and count them.',
    ],
    silenceSeconds: { whisper: 17, ritual: 52, deep: 104 },
  },
  {
    id: 'still-nothing-required',
    intent: 'still',
    title: 'Nothing Is Required',
    opening: 'For the length of this, you are needed nowhere.',
    invocation: [
      'Nothing is required of me here.',
      'Not improvement. Not insight. Not even calm.',
      'If the mind wanders, it wanders; I am not grading it.',
      'This is not a task disguised as a rest.',
      'Let me be, for a short while, unproductive and entirely permitted.',
      'The world will manage. It has been managing all along.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 7, holdOut: 1 }],
    groundingActions: [
      'Do nothing at all for two minutes. Set a timer so you can stop watching.',
      'Cancel one optional thing from tomorrow.',
      'Sit down somewhere comfortable with nothing in your hands.',
      'Step outside briefly and stand there without a purpose.',
    ],
    silenceSeconds: { whisper: 20, ritual: 60, deep: 120 },
  },
  {
    id: 'still-room-as-it-is',
    intent: 'still',
    title: 'The Room As It Is',
    opening: 'Attend to what is actually here.',
    invocation: [
      'Here is the room, unimproved, exactly as it is.',
      'The light in it. The sounds at its edges. The air, which has a temperature.',
      'I have been living in the room inside my head and neglecting this one.',
      'Let me notice five real things without needing them to be different.',
      'Presence is not a feeling I must produce.',
      'It is simply this: being where my body already is.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 6, holdOut: 1 }],
    groundingActions: [
      'Name five things you can see, four you can hear, and one you can feel.',
      'Open a window and stand at it for a minute.',
      'Clear one small surface in the room you are in.',
      'Touch something cold and pay attention to it for ten seconds.',
    ],
    silenceSeconds: { whisper: 15, ritual: 46, deep: 92 },
  },
  {
    id: 'still-ten-breaths',
    intent: 'still',
    title: 'Ten Quiet Breaths',
    opening: 'Ten breaths, honestly counted.',
    invocation: [
      'Ten breaths. That is the whole undertaking.',
      'Not a lifetime of calm. Not a changed temperament. Ten.',
      'If I lose the count, I begin again without complaint —',
      'losing the count is most of the practice.',
      'Let the numbers be plain and the breathing unremarkable.',
      'Small honest things, done fully, are how the noise gets smaller.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 6, holdOut: 0 }],
    groundingActions: [
      'Count ten more breaths before you pick anything up.',
      'Write one sentence about what matters next.',
      'Drink a glass of water and count the swallows.',
      'Sit still for sixty seconds without checking anything.',
    ],
    silenceSeconds: { whisper: 14, ritual: 44, deep: 88 },
  },
  {
    id: 'still-unhurried-hour',
    intent: 'still',
    title: 'The Unhurried Hour',
    opening: 'There is more time than the pulse suggests.',
    invocation: [
      'The urgency I feel is not the urgency of the situation.',
      'Almost nothing in this day is truly a matter of minutes.',
      'I let the pulse come down to meet the truth.',
      'Let me do the next thing at the speed it actually requires.',
      'Let me finish a sentence before beginning another.',
      'The hour is not chasing me. It never was.',
    ].join('\n'),
    breathPatterns: [{ inhale: 5, holdIn: 2, exhale: 7, holdOut: 0 }],
    groundingActions: [
      'Move one deadline that you invented yourself.',
      'Sit down for five minutes without an outcome in mind.',
      'Finish one thing completely before opening another.',
      'Take a slow walk to the end of the street and back.',
    ],
    silenceSeconds: { whisper: 16, ritual: 50, deep: 100 },
  },
  {
    id: 'still-return',
    intent: 'still',
    title: 'Return',
    opening: 'Wandering is not failure. Returning is the practice.',
    invocation: [
      'The mind will leave. It leaves constantly, and it is not a betrayal.',
      'The work is not staying. The work is returning.',
      'So: it has gone. Now it is back. That is one repetition.',
      'It will go again. It will come back again.',
      'Let me be patient with the going and generous with the return.',
      'This is how attention is trained: by forgiving it a thousand times.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 6, holdOut: 2 }],
    groundingActions: [
      'Return to the one task you abandoned today, for five minutes only.',
      'Notice the next time your attention leaves, and bring it back once.',
      'Put your phone down and pick your work back up without comment.',
      'Write one sentence about where your attention keeps going.',
    ],
    silenceSeconds: { whisper: 15, ritual: 47, deep: 94 },
  },
  {
    id: 'still-floor-beneath',
    intent: 'still',
    title: 'The Floor Beneath',
    opening: 'Begin with what is under you.',
    invocation: [
      'Whatever is true above the neck, this is true below it:',
      'there is a floor, and it is holding.',
      'Feet on it. Weight through it. Nothing required of me but contact.',
      'The body is not anxious; the body is in a room, doing its quiet work.',
      'Let me borrow its steadiness for a minute.',
      'The ground has never once let go.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 3, exhale: 7, holdOut: 0 }],
    groundingActions: [
      'Stand barefoot for one minute and feel the floor.',
      'Press both feet down firmly for a slow count of twenty.',
      'Step outside briefly and stand on the ground.',
      'Take five slow steps, noticing the weight shift each time.',
    ],
    silenceSeconds: { whisper: 14, ritual: 45, deep: 90 },
  },
  {
    id: 'still-let-day-land',
    intent: 'still',
    title: 'Let The Day Land',
    opening: 'The day is over. Let it be over.',
    invocation: [
      'The day is finished, though the mind is still running its errands.',
      'I am not on duty now.',
      'I let the unfinished things stay unfinished until morning,',
      'where they will be easier and I will be better.',
      'Let the last hours settle out of the shoulders.',
      'Nothing more is owed tonight.',
    ].join('\n'),
    breathPatterns: [
      { inhale: 4, holdIn: 0, exhale: 8, holdOut: 0 },
      { inhale: 4, holdIn: 2, exhale: 8, holdOut: 2 },
    ],
    groundingActions: [
      'Close the laptop and leave it closed for the rest of the evening.',
      'Write tomorrow one line, then stop working.',
      'Change out of the clothes you worked in.',
      'Wash your face and let the day end there.',
    ],
    silenceSeconds: { whisper: 18, ritual: 56, deep: 112 },
  },
  {
    id: 'still-small-now',
    intent: 'still',
    title: 'The Small Now',
    opening: 'Make the moment small enough to hold.',
    invocation: [
      'The future I am carrying is far too large to hold at once.',
      'So I make it small.',
      'Not this year. Not this week. This breath, and then the next.',
      'I can do a breath. Anyone can do a breath.',
      'Let the horizon come in close until it is a manageable size.',
      'Large things are only many small nows, arriving one at a time.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 2, exhale: 6, holdOut: 1 }],
    groundingActions: [
      'Write down only what happens in the next hour. Nothing beyond it.',
      'Do one small thing that takes under two minutes, and finish it.',
      'Drink a glass of water before thinking about anything else.',
      'Identify one thing you can control right now, and do that.',
    ],
    silenceSeconds: { whisper: 13, ritual: 42, deep: 86 },
  },
  {
    id: 'still-end-of-sentence',
    intent: 'still',
    title: 'The End Of The Sentence',
    opening: 'Let the thought finish and do not begin another.',
    invocation: [
      'I have been interrupting myself all day.',
      'Half-thoughts stacked on half-thoughts, none of them allowed to end.',
      'Let this one finish. Then let there be a pause.',
      'The pause is not empty; it is where thinking settles into knowing.',
      'I will not fill every silence in my own head.',
      'Let there be white space. Let the page breathe.',
    ].join('\n'),
    breathPatterns: [{ inhale: 4, holdIn: 3, exhale: 6, holdOut: 3 }],
    groundingActions: [
      'Finish reading one thing you started, all the way to the end.',
      'Write one complete sentence about what matters next, then stop.',
      'Leave a two-minute gap before your next task.',
      'Say one thing out loud and then stay quiet for ten seconds.',
    ],
    silenceSeconds: { whisper: 16, ritual: 49, deep: 98 },
  },
]
